from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from db.views import (
    getTest,
    postTest,
    deleteTest,
    create_corpus,
    update_corpus,
    get_corpus,
    delete_corpus,
    create_text,
    update_text,
    get_text,
    delete_text,
    find_similar_texts,
    search_texts_by_query,
    ontology_get_all_nodes,
    ontology_create_class,
    ontology_get_ontology,
    ontology_get_parent_classes,
    ontology_create_arc,
    ontology_create_arc_by_titles,
    ontology_all_nodes_and_arcs,
    ontology_node_by_uri,
    ontology_node_by_title,
    ontology_delete_node_by_uri,
    ontology_delete_arc_by_eid,
    ontology_run_query,
    ontology_get_class,
    ontology_get_class_by_title,
    ontology_get_class_parents,
    ontology_get_class_children,
    ontology_get_class_objects,
    ontology_update_class,
    ontology_delete_class,
    ontology_add_class_attribute,
    ontology_delete_class_attribute,
    ontology_add_class_object_attribute,
    ontology_delete_class_object_attribute,
    ontology_add_class_parent,
    ontology_create_object,
    ontology_get_object,
    ontology_update_object,
    ontology_delete_object,
    ontology_update_node,
    ontology_collect_signature,
)
schema_view = get_schema_view(
    openapi.Info(
        title="Your API",
        default_version='v1',
        description="API Documentation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],  # Разрешаем доступ всем
)

urlpatterns = [
    path('getTest',getTest , name='getTest'),
    path('postTest',postTest , name='postTest'),
    path('deleteTest',deleteTest , name='deleteTest'),
    # Corpus
    path('corpus/create', create_corpus, name='create_corpus'),
    path('corpus/update', update_corpus, name='update_corpus'),
    path('corpus/get', get_corpus, name='get_corpus'),
    path('corpus/delete', delete_corpus, name='delete_corpus'),
    # Text
    path('text/create', create_text, name='create_text'),
    path('text/update', update_text, name='update_text'),
    path('text/get', get_text, name='get_text'),
    path('text/delete', delete_text, name='delete_text'),
    path('text/find_similar', find_similar_texts, name='find_similar_texts'),
    path('text/search', search_texts_by_query, name='search_texts_by_query'),
    # Ontology
    path('ontology/nodes', ontology_get_all_nodes, name='ontology_get_all_nodes'),
    path('ontology/create_class', ontology_create_class, name='ontology_create_class'),
    path('ontology/ontology', ontology_get_ontology, name='ontology_get_ontology'),
    path('ontology/parent_classes', ontology_get_parent_classes, name='ontology_get_parent_classes'),
    path('ontology/create_arc', ontology_create_arc, name='ontology_create_arc'),
    path('ontology/create_arc_by_titles', ontology_create_arc_by_titles, name='ontology_create_arc_by_titles'),
    path('ontology/all_nodes_and_arcs', ontology_all_nodes_and_arcs, name='ontology_all_nodes_and_arcs'),
    path('ontology/node_by_uri', ontology_node_by_uri, name='ontology_node_by_uri'),
    path('ontology/node_by_title', ontology_node_by_title, name='ontology_node_by_title'),
    path('ontology/delete_node', ontology_delete_node_by_uri, name='ontology_delete_node_by_uri'),
    path('ontology/delete_arc', ontology_delete_arc_by_eid, name='ontology_delete_arc_by_eid'),
    path('ontology/run_query', ontology_run_query, name='ontology_run_query'),
    path('ontology/class', ontology_get_class, name='ontology_get_class'),
    path('ontology/class_by_title', ontology_get_class_by_title, name='ontology_get_class_by_title'),
    path('ontology/class_parents', ontology_get_class_parents, name='ontology_get_class_parents'),
    path('ontology/class_children', ontology_get_class_children, name='ontology_get_class_children'),
    path('ontology/class_objects', ontology_get_class_objects, name='ontology_get_class_objects'),
    path('ontology/update_class', ontology_update_class, name='ontology_update_class'),
    path('ontology/delete_class', ontology_delete_class, name='ontology_delete_class'),
    path('ontology/add_class_attribute', ontology_add_class_attribute, name='ontology_add_class_attribute'),
    path('ontology/delete_class_attribute', ontology_delete_class_attribute, name='ontology_delete_class_attribute'),
    path('ontology/add_class_object_attribute', ontology_add_class_object_attribute, name='ontology_add_class_object_attribute'),
    path('ontology/delete_class_object_attribute', ontology_delete_class_object_attribute, name='ontology_delete_class_object_attribute'),
    path('ontology/add_class_parent', ontology_add_class_parent, name='ontology_add_class_parent'),
    path('ontology/create_object', ontology_create_object, name='ontology_create_object'),
    path('ontology/object', ontology_get_object, name='ontology_get_object'),
    path('ontology/update_object', ontology_update_object, name='ontology_update_object'),
    path('ontology/delete_object', ontology_delete_object, name='ontology_delete_object'),
    path('ontology/update_node', ontology_update_node, name='ontology_update_node'),
    path('ontology/collect_signature', ontology_collect_signature, name='ontology_collect_signature'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0)),
]